site_name: SSE Documentation Example

nav:
    - Home: 'index.md'
    - 'User Guide':
        - 'Installation': 'compilation-and-installation.md'
        - 'Getting Started': 'how-to.md'

repo_url: https://github.com/chlai1012/sse-mkdocs-exercise.git
edit_uri: edit/main/docs/